apiVersion: v1
kind: ConfigMap
metadata:
  name: my-backstage-config-cm1 # placeholder for <bs>-default-appconfig
data:
  default.app-config.yaml: |
    backend:
      auth:
        keys:
          # This is a default value, which you should change by providing your own app-config
          - secret: "pl4s3Ch4ng3M3"