apiVersion: v1
kind: Service
metadata:
  name: # placeholder for 'backstage-<cr-name>'
spec:
  type: ClusterIP
  selector:
    janus-idp.io/app:  # placeholder for 'backstage-<cr-name>'
  ports:
    - name: http-backend
      port: 7007
      targetPort: backend