# permissions for end users to edit backstagedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backstagedeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backstage-deploy-operator
    app.kubernetes.io/part-of: backstage-deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: backstage-editor-role
rules:
- apiGroups:
  - backstage.io
  resources:
  - backstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backstage.io
  resources:
  - backstagedes/status
  verbs:
  - get
