# permissions for namespace admins to enable operator to get list of files to mount from a secret
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backstage-secret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backstage-operator
    app.kubernetes.io/part-of: backstage-operator
    app.kubernetes.io/managed-by: kustomize
  name: backstage-secret-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch