apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: backstage-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: backstage-operator
  source: backstage-operator
  sourceNamespace: openshift-marketplace
  startingCSV: backstage-deploy-operator.v0.1.0
