apiVersion: janus-idp.io/v1alpha1
kind: Backstage
metadata:
  name: bs-existing-secret
  namespace: backstage
spec:
  enableLocalDb: true
  existingDbSecret:
    name: existing-postgres-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: existing-postgres-secret
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin123
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRESQL_ADMIN_PASSWORD: admin123
  POSTGRES_HOST: backstage-psql-bs-existing-secret
