apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: bs-existing-secret
spec:
  database:
    enableLocalDb: true
    authSecretName: existing-postgres-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: existing-postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "admin123"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRESQL_ADMIN_PASSWORD: "admin123"
  POSTGRES_HOST: "backstage-psql-bs-existing-secret"
